default:
  tags:
    - CREMI 
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

buid-job1:
  stage: build
  script :
    - pip install coverage

test-job1:
  stage: test
  script :
    - python3 -m unittest -v test_parser.py

coverage-job1:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run --source=Parser -m pytest test_parser.py
    - coverage report -m

